#if !canImport(ObjectiveC)
import XCTest

extension OctoidTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OctoidTests = [
        ("testEventDecoding", testEventDecoding),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OctoidTests.__allTests__OctoidTests),
    ]
}
#endif
